version: "3"

dotenv:
  - .env

includes:
  goose:
    taskfile: ./db/migrate/Taskfile.yml
    dir: ./db/migrate

  sqlc:
    taskfile: ./db/Taskfile.yml
    dir: ./db

tasks:
  default:
    deps:
      - server
      - worker

  server:
    desc: Run the HTTP server.
    aliases:
      - serve
      - s
    cmds:
      - air

  worker:
    desc: Run the background worker.
    aliases:
      - work
      - w
    cmds:
      - air -c .air.worker.toml
