version: "3"

dotenv:
  - .env

includes:
  goose:
    taskfile: ./db/migrate/Taskfile.yml
    dir: ./db/migrate

  sqlc:
    taskfile: ./db/Taskfile.yml
    dir: ./db

tasks:
  server:
    desc: Run the HTTP server.
    aliases:
      - s
    cmds:
      - air
