# This file is heavily templatized which breaks syntax highlighting in
# most editors. Don't worry about it.
env = "production"

[server]
host = "0.0.0.0"
port = {{.Port}}

[database]
conn = "{{.DatabaseConn}}"
migrate = true

[airbrake]
project_id = {{.AirbrakeProjectID}}
project_key = "{{.AirbrakeProjectKey}}"

[worker]
concurrency = 10
redis_url = "{{.RedisURL}}"
