version: "3"

env:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

tasks:
  compile:
    desc: Generate Go code from SQL queries.
    sources:
      - sqlc.yaml
      - "./migrate/*.sql"
      - "./sql/*.sql"
    cmds:
      - sqlc generate

  compile:watch:
    desc: Watch for SQL query changes and recompile.
    cmds:
      - wgo -file '.sql$' sqlc generate

  drop:
    desc: Drop the database. Irreversible.
    dir: ./migrate
    ignore_error: true
    preconditions:
      - sh: '[ "$VERSO_ENV" = "development" ] || [ "$VERSO_ENV" = "test" ]'
        msg: "Command can only be run in development or test"
    cmds:
      - psql postgres --command 'drop database {{.DATABASE_NAME}}';

  create:
    desc: Create the database.
    dir: ./migrate
    cmds:
      - psql postgres --command 'create database {{.DATABASE_NAME}};'

  seed:
    desc: Seed the database with fixture data.
    dir: ..
    cmds:
      - psql --quiet --output=/dev/null --dbname={{.DATABASE_NAME}} --file db/seed.sql

  seed:dump:
    desc: Dumps the dev database to a seed file.
    dir: ..
    cmds:
      - pg_dump --data-only --exclude-table=goose_db_version {{.DATABASE_NAME}} > db/seed.sql

  gen:
    desc: Generate a new migration.
    dir: ./migrate
    cmds:
      - goose create {{.CLI_ARGS}} sql

  migrate:
    desc: Migrate to the latest version.
    dir: ./migrate
    cmds:
      - goose up

  migrate:lint:
    desc: Lint migrations.
    dir: ./migrate
    cmds:
      - squawk *.sql

  rollback:
    desc: Roll back the last migration. Irreversible.
    dir: ./migrate
    cmds:
      - goose down

  redo:
    desc: Roll back and reapply the last migration.
    dir: ./migrate
    cmds:
      - goose redo

  reset:
    desc: Roll back and reapply all migrations.
    dir: ./migrate
    cmds:
      - task: drop
      - task: create
      - task: migrate
      - task: compile
      - task: seed

  status:
    desc: Show migration status.
    dir: ./migrate
    cmds:
      - goose status
