// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package query

import (
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID        int32
	Uuid      uuid.UUID
	Title     string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
}
