// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package query

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ContentRssFeed struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Title     string    `json:"title"`
	Url       string    `json:"url"`
}

type ContentRssItem struct {
	ID              int64        `json:"id"`
	Uuid            uuid.UUID    `json:"uuid"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	RssFeedID       int64        `json:"rss_feed_id"`
	RssGuid         string       `json:"rss_guid"`
	Title           string       `json:"title"`
	Link            string       `json:"link"`
	Content         string       `json:"content"`
	PublishedAt     sql.NullTime `json:"published_at"`
	RemoteUpdatedAt sql.NullTime `json:"remote_updated_at"`
}
