// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package query

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID        int32     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	Title     string    `json:"title"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Item struct {
	ID              int32          `json:"id"`
	Uuid            uuid.UUID      `json:"uuid"`
	FeedID          int32          `json:"feed_id"`
	Title           sql.NullString `json:"title"`
	Link            sql.NullString `json:"link"`
	Content         sql.NullString `json:"content"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	RemoteUpdatedAt sql.NullTime   `json:"remote_updated_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
