// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (title, url) VALUES ($1, $2)
RETURNING id, uuid, title, url, created_at, updated_at
`

type CreateFeedParams struct {
	Title string `json:"title"`
	Url   string `json:"url"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.Title, arg.Url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeed = `-- name: GetFeed :one
SELECT id, uuid, title, url, created_at, updated_at FROM feeds
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetFeed(ctx context.Context, uuid uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, uuid)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, uuid, title, url, created_at, updated_at FROM feeds
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
