// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: queue_items.sql

package query

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createQueueItem = `-- name: CreateQueueItem :one
insert into content.queue_items (user_id, rss_item_id)
  values ($1, $2)
  on conflict do nothing
  returning id, uuid, created_at, updated_at, user_id, rss_item_id, is_read
`

type CreateQueueItemParams struct {
	UserID    int64         `json:"user_id"`
	RssItemID sql.NullInt64 `json:"rss_item_id"`
}

func (q *Queries) CreateQueueItem(ctx context.Context, arg CreateQueueItemParams) (ContentQueueItem, error) {
	row := q.db.QueryRowContext(ctx, createQueueItem, arg.UserID, arg.RssItemID)
	var i ContentQueueItem
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RssItemID,
		&i.IsRead,
	)
	return i, err
}

const getQueueItemsByUserId = `-- name: GetQueueItemsByUserId :many
select ri.id, ri.uuid, ri.created_at, ri.updated_at, rss_feed_id, rss_guid, title, link, content, published_at, remote_updated_at, queue_items.id, queue_items.uuid, queue_items.created_at, queue_items.updated_at, user_id, rss_item_id, is_read from content.rss_items ri
  join content.queue_items on queue_items.rss_item_id = ri.id
  where queue_items.user_id = $1 
  order by ri.id desc
  limit $2
`

type GetQueueItemsByUserIdParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetQueueItemsByUserIdRow struct {
	ID              int64         `json:"id"`
	Uuid            uuid.UUID     `json:"uuid"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	RssFeedID       int64         `json:"rss_feed_id"`
	RssGuid         string        `json:"rss_guid"`
	Title           string        `json:"title"`
	Link            string        `json:"link"`
	Content         string        `json:"content"`
	PublishedAt     sql.NullTime  `json:"published_at"`
	RemoteUpdatedAt sql.NullTime  `json:"remote_updated_at"`
	ID_2            int64         `json:"id_2"`
	Uuid_2          uuid.UUID     `json:"uuid_2"`
	CreatedAt_2     time.Time     `json:"created_at_2"`
	UpdatedAt_2     time.Time     `json:"updated_at_2"`
	UserID          int64         `json:"user_id"`
	RssItemID       sql.NullInt64 `json:"rss_item_id"`
	IsRead          bool          `json:"is_read"`
}

func (q *Queries) GetQueueItemsByUserId(ctx context.Context, arg GetQueueItemsByUserIdParams) ([]GetQueueItemsByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getQueueItemsByUserId, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQueueItemsByUserIdRow
	for rows.Next() {
		var i GetQueueItemsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RssFeedID,
			&i.RssGuid,
			&i.Title,
			&i.Link,
			&i.Content,
			&i.PublishedAt,
			&i.RemoteUpdatedAt,
			&i.ID_2,
			&i.Uuid_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.UserID,
			&i.RssItemID,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
