// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: rss_feeds.sql

package query

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRssFeed = `-- name: CreateRssFeed :one
insert into rss.feeds (title, url) values ($1, $2) returning id, uuid, created_at, updated_at, title, url, active, last_crawled_at
`

type CreateRssFeedParams struct {
	Title string `json:"title"`
	Url   string `json:"url"`
}

func (q *Queries) CreateRssFeed(ctx context.Context, arg CreateRssFeedParams) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, createRssFeed, arg.Title, arg.Url)
	var i RssFeed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Active,
		&i.LastCrawledAt,
	)
	return i, err
}

const findOrCreateRssFeed = `-- name: FindOrCreateRssFeed :one
with inserted as (
  insert into rss.feeds (
    title,
    url
  ) select $1, $2 where not exists (
    select 1 from rss.feeds where url = $2
  ) returning id, uuid, created_at, updated_at, title, url, active, last_crawled_at
) select id, uuid, created_at, updated_at, title, url, active, last_crawled_at from inserted
  union
  select id, uuid, created_at, updated_at, title, url, active, last_crawled_at from rss.feeds where url = $2
`

type FindOrCreateRssFeedParams struct {
	Title string `json:"title"`
	Url   string `json:"url"`
}

type FindOrCreateRssFeedRow struct {
	ID            int64        `json:"id"`
	Uuid          uuid.UUID    `json:"uuid"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	Title         string       `json:"title"`
	Url           string       `json:"url"`
	Active        bool         `json:"active"`
	LastCrawledAt sql.NullTime `json:"last_crawled_at"`
}

func (q *Queries) FindOrCreateRssFeed(ctx context.Context, arg FindOrCreateRssFeedParams) (FindOrCreateRssFeedRow, error) {
	row := q.db.QueryRowContext(ctx, findOrCreateRssFeed, arg.Title, arg.Url)
	var i FindOrCreateRssFeedRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Active,
		&i.LastCrawledAt,
	)
	return i, err
}

const findRssFeed = `-- name: FindRssFeed :one
select id, uuid, created_at, updated_at, title, url, active, last_crawled_at from rss.feeds
where id = $1 limit 1
`

func (q *Queries) FindRssFeed(ctx context.Context, id int64) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, findRssFeed, id)
	var i RssFeed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Active,
		&i.LastCrawledAt,
	)
	return i, err
}

const findRssFeedByUrl = `-- name: FindRssFeedByUrl :one
select id, uuid, created_at, updated_at, title, url, active, last_crawled_at from rss.feeds
where url = $1 limit 1
`

func (q *Queries) FindRssFeedByUrl(ctx context.Context, url string) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, findRssFeedByUrl, url)
	var i RssFeed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Active,
		&i.LastCrawledAt,
	)
	return i, err
}

const findRssFeedByUuid = `-- name: FindRssFeedByUuid :one
select id, uuid, created_at, updated_at, title, url, active, last_crawled_at from rss.feeds
where uuid = $1 limit 1
`

func (q *Queries) FindRssFeedByUuid(ctx context.Context, uuid uuid.UUID) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, findRssFeedByUuid, uuid)
	var i RssFeed
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Active,
		&i.LastCrawledAt,
	)
	return i, err
}
