// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: rss_subscriptions.sql

package query

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
with inserted as (
  insert into rss.subscriptions (
    user_id,
    feed_id
  ) select $1, $2 where not exists (
    select 1 from rss.subscriptions where user_id = $1 and feed_id = $2
  ) returning id, uuid, created_at, updated_at, user_id, feed_id, custom_title
)
select id, uuid, created_at, updated_at, user_id, feed_id, custom_title from inserted
  union
  select id, uuid, created_at, updated_at, user_id, feed_id, custom_title from rss.subscriptions where user_id = $1 and feed_id = $2
`

type CreateSubscriptionParams struct {
	UserID int64 `json:"user_id"`
	FeedID int64 `json:"feed_id"`
}

type CreateSubscriptionRow struct {
	ID          int64          `json:"id"`
	Uuid        uuid.UUID      `json:"uuid"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UserID      int64          `json:"user_id"`
	FeedID      int64          `json:"feed_id"`
	CustomTitle sql.NullString `json:"custom_title"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error) {
	row := q.db.QueryRowContext(ctx, createSubscription, arg.UserID, arg.FeedID)
	var i CreateSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.CustomTitle,
	)
	return i, err
}

const getSubscribersByFeedId = `-- name: GetSubscribersByFeedId :many
select id, uuid, created_at, updated_at, user_id, feed_id, custom_title from rss.subscriptions s
  where s.feed_id = $1
`

func (q *Queries) GetSubscribersByFeedId(ctx context.Context, feedID int64) ([]RssSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscribersByFeedId, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RssSubscription
	for rows.Next() {
		var i RssSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.CustomTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
