// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: rss_items.sql

package query

import (
	"context"
	"database/sql"
)

const createRssItem = `-- name: CreateRssItem :one
insert into content.rss_items as i (
  rss_feed_id,
  rss_guid,
  title,
  link,
  content,
  published_at,
  remote_updated_at
) values ($1, $2, $3, $4, $5, $6, $7)
  on conflict (rss_feed_id, rss_guid) do update
  set
    title = excluded.title, 
    link = excluded.link, 
    content = excluded.content,
    published_at = excluded.published_at,
    remote_updated_at = excluded.remote_updated_at
  -- only perform insert if these values are changed, in order to avoid the
  -- rss_item_versions_insert_on_item_update trigger on updates to this table
  where
    i.title is distinct from excluded.title or 
    i.link is distinct from excluded.link or 
    i.content is distinct from excluded.content or
    i.published_at is distinct from excluded.published_at or
    i.remote_updated_at is distinct from excluded.remote_updated_at
  returning id, uuid, created_at, updated_at, rss_feed_id, rss_guid, title, link, content, published_at, remote_updated_at
`

type CreateRssItemParams struct {
	RssFeedID       int64        `json:"rss_feed_id"`
	RssGuid         string       `json:"rss_guid"`
	Title           string       `json:"title"`
	Link            string       `json:"link"`
	Content         string       `json:"content"`
	PublishedAt     sql.NullTime `json:"published_at"`
	RemoteUpdatedAt sql.NullTime `json:"remote_updated_at"`
}

func (q *Queries) CreateRssItem(ctx context.Context, arg CreateRssItemParams) (ContentRssItem, error) {
	row := q.db.QueryRowContext(ctx, createRssItem,
		arg.RssFeedID,
		arg.RssGuid,
		arg.Title,
		arg.Link,
		arg.Content,
		arg.PublishedAt,
		arg.RemoteUpdatedAt,
	)
	var i ContentRssItem
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RssFeedID,
		&i.RssGuid,
		&i.Title,
		&i.Link,
		&i.Content,
		&i.PublishedAt,
		&i.RemoteUpdatedAt,
	)
	return i, err
}

const getRssItemsByRssFeedId = `-- name: GetRssItemsByRssFeedId :many
select id, uuid, created_at, updated_at, rss_feed_id, rss_guid, title, link, content, published_at, remote_updated_at from content.rss_items where rss_items.rss_feed_id = $1 limit $2
`

type GetRssItemsByRssFeedIdParams struct {
	RssFeedID int64 `json:"rss_feed_id"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) GetRssItemsByRssFeedId(ctx context.Context, arg GetRssItemsByRssFeedIdParams) ([]ContentRssItem, error) {
	rows, err := q.db.QueryContext(ctx, getRssItemsByRssFeedId, arg.RssFeedID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentRssItem
	for rows.Next() {
		var i ContentRssItem
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RssFeedID,
			&i.RssGuid,
			&i.Title,
			&i.Link,
			&i.Content,
			&i.PublishedAt,
			&i.RemoteUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
