// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: taxonomy_tags.sql

package query

import (
	"context"
)

const createTag = `-- name: CreateTag :one
insert into taxonomy.tags (
  name,
  user_id
)
values ($1, $2)
returning id, uuid, created_at, updated_at, user_id, name
`

type CreateTagParams struct {
	Name   string `json:"name"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (TaxonomyTag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.UserID)
	var i TaxonomyTag
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
	)
	return i, err
}

const getTagsByUserID = `-- name: GetTagsByUserID :many
select id, uuid, created_at, updated_at, user_id, name from taxonomy.tags
where user_id = $1
`

func (q *Queries) GetTagsByUserID(ctx context.Context, userID int64) ([]TaxonomyTag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxonomyTag
	for rows.Next() {
		var i TaxonomyTag
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
