// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: taxonomy_rss_feed_tags.sql

package query

import (
	"context"
)

const createRSSFeedTag = `-- name: CreateRSSFeedTag :one
insert into taxonomy.rss_feed_tags (
  tag_id,
  rss_feed_id
)
values ($1, $2)
returning id, uuid, created_at, updated_at, tag_id, rss_feed_id
`

type CreateRSSFeedTagParams struct {
	TagID     int64 `json:"tag_id"`
	RSSFeedID int64 `json:"rss_feed_id"`
}

func (q *Queries) CreateRSSFeedTag(ctx context.Context, arg CreateRSSFeedTagParams) (TaxonomyRssFeedTag, error) {
	row := q.db.QueryRowContext(ctx, createRSSFeedTag, arg.TagID, arg.RSSFeedID)
	var i TaxonomyRssFeedTag
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TagID,
		&i.RSSFeedID,
	)
	return i, err
}
