name: Build

env:
  GO_PRIVATE: github.com/versolabs/*
  VERSO_ENV: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: verso_ci
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - run: git config --global url."https://${{ secrets.TOKEN }}:@github.com/".insteadOf "https://github.com"
      - run: go mod download
      - run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - run: ./bin/task db:reset
      - run: go build -v ./...
      - run: go test -v ./...
